#+title: JSONファイルの書き方

* 敵キャラクター情報の記述方法
** 例
#+BEGIN_SRC json
{
    "magic": "enemy_description",
    "enemy": [
        {
            "name": "Fairy",
            "TextureID": "FLOWER1",
            "point": {
                "x": 0,
                "y": 0
            },
            "scale": {
                "x": 0,
                "y": 0
            },
            "move_func_description": {
                "type": "unit",
                "ID": "VECTOR_LINEAR",
                "speed_x": 10,
                "speed_y": 10
            },
            "rot_func_description": {
                "type": "unit",
                "ID": "STOP"
            },
            "max_hp": 100,
            "init_hp": 100,
            "radius": 10
            "shot": [
                {
                    "function_name": "multi_shot",
                    "time": 30,
                    "at": {
                        "x": 0,
                        "y": 0
                    }
                }
            ]
        }
    ]
}
#+END_SRC
** 説明
*** magic
ここのフィールドには何を定義しているかを書く。敵キャラクターの情報を書きたい場合は *enemy_description* と記述すること。
*** enemy
この仕様では、一つのファイルに複数の敵キャラクター情報を記述することができる。enemyフィールドには敵キャラクターの情報の配列
を記述する。一つのオブジェクトの仕様は以下で説明する。
**** name
このフィールドには敵キャラクターの名前を記述する。この文字列はデータ特定のために利用されるため、重複を防ぐこと。
**** TextureID
このフィールドには include/textures.hpp で定義されたTextureIDを記述する。このテクスチャが敵キャラクターのテクスチャになる。
**** point
このフィールドには敵キャラクターが現れる座標を書く。
***** x
現れるX座標
***** y
現れるY座標
**** scale
敵キャラクターのテクスチャのスケールを指定する。
***** x
X座標のスケール
***** y
Y座標のスケール
**** move_func_description
敵キャラクターの移動方法の定義を行う。記述方法は弾幕の移動方法と同じ。各フィールドは移動関数によって異なる。
typeとIDは必ず記述することになる。
**** rot_func_description
敵キャラクターの回転方法の定義を行う。
**** max_hp
敵キャラクターの最大HP
**** init_hp
敵キャラクターの初期HP
**** radius
敵キャラクターの当たり判定の半径
**** shot
敵キャラクターが放つ弾幕の設定を配列形式で記述する。一つのオブジェクトの記述方法を次に示す。
***** function_name
他jsonファイルで定義された関数を呼び出すことが出来る。このフィールドには予め定義した関数名を記述する。
***** time
このフィールドには弾幕の相対発射時間を記述する。つまり、この敵がフィールドに生成されてからの時間を指定する。
***** at
このフィールドには弾幕の相対発射位置を記述する。
このフィールドを記述しない場合、相対位置(0, 0)として弾幕が発射される。
****** x
相対X座標
****** y
相対Y座標
